# use oracle_enhanced adapter to connect oracle database
development:
  adapter: oracle_enhanced
  database: 192.168.1.8/orcl
  #database: 116.236.235.154/orcl
  #database: 114.80.138.164/orcl
  username: "jjsc_web_production"
  password: "jjsc_web_production"
  #password: "3344134"
  encoding: utf8
  wlfp:
    adapter: mysql2
    database: wlfp
    host: 116.236.235.154
    username: wlfp
    password: 'wlfp'
    encoding: utf8
    


production:
  adapter: oracle_enhanced
  database: 192.168.1.8/orcl
#  database: 192.168.100.10/orcl
  username: "jjsc_web_production"
  password: "jjsc_web_production"
  encoding: utf8
  wlfp:
    adapter: mysql2
    database: wlfp
    host: 192.168.1.14
    username: root
    password: '3344134'
    encoding: utf8

test:
  adapter: oracle_enhanced
  database: 192.168.1.8/orcl
# database: 192.168.100.10/orcl
  username: "jjsc_web_test"
  password: "jjsc_web_test"
  encoding: utf8
